version: '3.9'

services:
  database:
    image: postgres:15
    container_name: examensarbete-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookwishlist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examensarbete-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/bookwishlist
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
